name: Overwrite .env

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite .env
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: .env
          write-mode: overwrite
          contents: |
            # REACT_APP_MODE='development'
            REACT_APP_MODE='production'
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions'