name: Overwrite ip

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Overwrite ip.js
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: src/ip.js
          write-mode: overwrite
          contents: |
            const ip = 'https://pi3-incommun-backend.herokuapp.com'
            export default ip
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions - ${date}'