# This is a basic workflow to help you get started with Actions

name: Overwrite src/config.js && Dupe backend/

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwite config.js
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: backend/src/config.js
          write-mode: overwrite
          contents: |
            module.exports = {
              jwtSecret: '${{ secrets.JWT_SECRET }}'
            }

      - name: Push the backend folder to pi3-incommun-heroku-backend
        id: push_backend
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'backend'
          destination-github-username: 'alexandre97costa'
          destination-repository-name: 'pi3-incommun-heroku-backend'
          user-email: alexandre97costa@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
